# Generated by Django 5.1.3 on 2025-02-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto',
        ),
    ]
