<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-02-19 12:57
=======
# Generated by Django 5.1.6 on 2025-02-19 12:53
>>>>>>> a77b5d777e7bf2b608827958df88ac334517cce9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
=======
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('caracteristicas', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
>>>>>>> a77b5d777e7bf2b608827958df88ac334517cce9
            ],
        ),
    ]
